

# Image/chart registry — overridable via dev.env (it is env-specific). The
# product VERSIONS below are intentionally NOT overridable from dev.env: they
# are code-bound and git-controlled (see the ':=' after the include).
REGISTRY ?= quay.io/kubotal

# Per-developer overrides (git-ignored, optional).
# The leading '-' makes a missing file a silent no-op, so this never breaks.
# If you use the registry set with 'make dev-up', the same values are sourced
# by the hack/ scripts; see dev.env.example.
-include dev.env


APP_VERSION ?= 0.1.0-snapshot
HELM_VERSION ?= 0.1.0-snapshot

IMG_REPO ?= $(REGISTRY)/exec/kindex

HELM_DOCKER_REPO := $(REGISTRY)/charts


BUILD_TS ?= $(shell date -u +%Y%m%d.%H%M%S)
# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

# CONTAINER_TOOL defines the container tool to be used for building images.
# Be aware that the target commands are only tested with Docker which is
# scaffolded by default. However, you might want to replace it to use other
# tools. (i.e. podman)
CONTAINER_TOOL ?= docker



.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

##@ Development

.PHONY: version
version: ## Set version in binary
	@echo "// Generated by Makefile\n\npackage global\n\nvar Version = \"$(APP_VERSION)\"\nvar BuildTs = \"$(BUILD_TS)\"\n" >internal/global/version_.go


##@ Build

.PHONY: build
build: ## Build binary.
	CGO_ENABLED=0 go build -o bin/kindex main.go



##@ Docker

.PHONY: docker
docker: version docker-build docker-push  ## Build controller docker image and push

.PHONY: docker-build
docker-build: version ## Build docker image
	$(CONTAINER_TOOL) build -t $(IMG_REPO):$(APP_VERSION) .

.PHONY: docker-push
docker-push: ## Push docker image
	$(CONTAINER_TOOL) push $(IMG_REPO):$(APP_VERSION)

# PLATFORMS defines the target platforms for the manager image be built to provide support to multiple
# architectures. (i.e. make docker-buildx IMG=myregistry/mypoperator:0.0.1). To use this option you need to:
# - be able to use docker buildx. More info: https://docs.docker.com/build/buildx/
# - have enabled BuildKit. More info: https://docs.docker.com/develop/develop-images/build_enhancements/
# - be able to push the image to your registry
PLATFORMS ?= linux/arm64,linux/amd64
.PHONY: docker-buildx
docker-buildx: version  ## Build and push docker image with cross-platform support
	- $(CONTAINER_TOOL) buildx create --name kindex-builder --driver=docker-container
	- $(CONTAINER_TOOL) buildx build --builder kindex-builder --push --platform=$(PLATFORMS) --tag $(IMG_REPO):$(APP_VERSION) -f Dockerfile .
	- $(CONTAINER_TOOL) buildx rm kindex-builder



##@ Helm

define CHART_YAML
# File generated by Makefile
apiVersion: v2
name: kindex
version: $(HELM_VERSION)
appVersion: $(APP_VERSION)
description: "Very simple test server"
annotations:
  kubotal_image_repository: $(IMG_REPO)
endef
export CHART_YAML

.PHONY: chart-yaml
chart-yaml: ## Generate the helm/kindex/Chart.yaml
	echo "$$CHART_YAML" >./helm/kindex/Chart.yaml

.PHONY: chart
chart: chart-yaml  ## Build and push helm chart
	cd ./helm && helm package -d ./../tmp kindex && helm push ./../tmp/kindex-${HELM_VERSION}.tgz oci://${HELM_DOCKER_REPO}


