

# Image and chart registry — Must be set via dev.env or from environment.
# Intentionally empty in this makefile, as we want user to set REGISTRY
# explicitly. Targets that need it depend on `check-registry`, which fails with
# a clear message when it is unset.
REGISTRY ?=

# Per-developer overrides (git-ignored, optional).
# The leading '-' makes a missing file a silent no-op, so this never breaks.
# If you use the registry set with 'make dev-up', the same values are sourced
# by the hack/ scripts; see dev.env.example.
-include dev.env

# The product VERSIONS below are intentionally NOT overridable from dev.env or from environment.
# They are code-bound and git-controlled (see the ':=' assignment type).

APP_VERSION := 0.1.0-snapshot
HELM_VERSION := 0.1.0-snapshot

IMG_REPO := $(REGISTRY)/exec/kindex

HELM_DOCKER_REPO := $(REGISTRY)/charts


BUILD_TS ?= $(shell date -u +%Y%m%d.%H%M%S)

# Version/build stamped into the binary at link time.
LDFLAGS := -X kindex/internal/global.Version=$(APP_VERSION) -X kindex/internal/global.BuildTs=$(BUILD_TS)


# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

# CONTAINER_TOOL defines the container tool to be used for building images.
# Be aware that the target commands are only tested with Docker which is
# scaffolded by default. However, you might want to replace it to use other
# tools. (i.e. podman)
CONTAINER_TOOL ?= docker


.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)


##@ Build

.PHONY: check-registry
check-registry: ## Fail with a clear message if REGISTRY is not set
	@if [ -z "$(strip $(REGISTRY))" ]; then \
		echo "ERROR: REGISTRY is not set."; \
		echo "Set it in dev.env, export it in your environment, or pass it on the command line, e.g.:"; \
		echo "    make $(or $(MAKECMDGOALS),<target>) REGISTRY=quay.io/my-organization"; \
		exit 1; \
	fi

.PHONY: display
display:  ## Display current config values
	@echo "---------"
	@echo "REGISTRY: $(REGISTRY)"
	@echo "APP_VERSION: $(APP_VERSION)"
	@echo "HELM_VERSION: $(HELM_VERSION)"
	@echo "---------"

.PHONY: build
build: display ## Build binary.
	CGO_ENABLED=0 go build -ldflags '$(LDFLAGS)' -o bin/kindex main.go


##@ Docker

.PHONY: docker
docker: display docker-build docker-push  ## Build controller docker image and push

.PHONY: docker-build
docker-build: check-registry ## Build docker image
	$(CONTAINER_TOOL) build --build-arg VERSION=$(APP_VERSION) --build-arg BUILD_TS=$(BUILD_TS) -t $(IMG_REPO):$(APP_VERSION) .

.PHONY: docker-push
docker-push: check-registry ## Push docker image
	$(CONTAINER_TOOL) push $(IMG_REPO):$(APP_VERSION)

# PLATFORMS defines the target platforms for the manager image be built to provide support to multiple
# architectures. (i.e. make docker-buildx IMG=myregistry/mypoperator:0.0.1). To use this option you need to:
# - be able to use docker buildx. More info: https://docs.docker.com/build/buildx/
# - have enabled BuildKit. More info: https://docs.docker.com/develop/develop-images/build_enhancements/
# - be able to push the image to your registry
PLATFORMS ?= linux/arm64,linux/amd64
.PHONY: docker-buildx
docker-buildx: check-registry display  ## Build and push docker image with cross-platform support
	- $(CONTAINER_TOOL) buildx create --name kindex-builder --driver=docker-container
	- $(CONTAINER_TOOL) buildx build --builder kindex-builder --push --platform=$(PLATFORMS) --build-arg VERSION=$(APP_VERSION) --build-arg BUILD_TS=$(BUILD_TS) --tag $(IMG_REPO):$(APP_VERSION) -f Dockerfile .
	- $(CONTAINER_TOOL) buildx rm kindex-builder


##@ Helm

define CHART_YAML
# File generated by Makefile
apiVersion: v2
name: kindex
version: $(HELM_VERSION)
appVersion: $(APP_VERSION)
description: "Very simple test server"
annotations:
  kubotal_image_repository: $(IMG_REPO)
endef
export CHART_YAML

.PHONY: chart-yaml
chart-yaml: check-registry ## Generate the helm/kindex/Chart.yaml
	echo "$$CHART_YAML" >./helm/kindex/Chart.yaml

.PHONY: chart
chart: display chart-yaml  ## Build and push helm chart
	cd ./helm && helm package -d ./../tmp kindex && helm push ./../tmp/kindex-${HELM_VERSION}.tgz oci://${HELM_DOCKER_REPO}


